# fly.toml app configuration file generated for mindwise-backend on 2025-08-31
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mindwise-backend"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/health"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"