name = "mindwise-frontend"
compatibility_date = "2025-08-31"
pages_build_output_dir = ".next"

[build]
command = "npm run build"
watch_dir = "apps/frontend/src"

[vars]
NEXT_PUBLIC_SUPABASE_URL = "${NEXT_PUBLIC_SUPABASE_URL}"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "${NEXT_PUBLIC_SUPABASE_ANON_KEY}"
NEXT_PUBLIC_API_BASE_URL = "${NEXT_PUBLIC_API_BASE_URL}"