name: Monorepo CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci

      - name: Lint frontend
        run: |
          cd apps/frontend
          npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: Lint backend
        run: |
          cd apps/backend
          npx eslint . --ext .js,.ts

  test:
    name: Test Applications
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          cd apps/frontend && npm ci
          cd ../backend && npm ci

      - name: Run frontend tests
        run: |
          cd apps/frontend
          npm run test

      - name: Run backend tests
        run: |
          cd apps/backend
          npm run test

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Audit frontend dependencies
        run: |
          cd apps/frontend
          npm audit --audit-level=moderate

      - name: Audit backend dependencies
        run: |
          cd apps/backend
          npm audit --audit-level=moderate